### ISSUE TITLE
chart.Serializer.Reset() throws an exception

### ISSUE THREAD

**Issue by KirillKornienko** [dotnet/winforms-datavisualization#24]
static void Main(string[] args)
        {
            var chart = new Chart();
            chart.Serializer.Reset();
        }

"System.ArgumentException: "Object of type 'System.Windows.Size' cannot be converted to type 'System.Drawing.Size'."

Reset() throws an exception in .Net Core 3.0/3.1. But this code works correctly in integrated Charting in .Net Framework.

**Comment by weltkante** [comment]
As the discussion over at dotnet/runtime#812 resolved this was a porting bug, .NET Core adds a reference to WindowsBase which was not present in Desktop Framework. This leads to the type `System.Windows.Size` (from WPF) being accessible, since charting lives in namespace `System.Windows.Forms.DataVisualization.Charting` which is below `System.Windows` any unqualified use of `Size` will use the class from WindowsBase instead of System.Drawing without producing an error.

So this needs to be fixed in the source project, can someone get attention to it? In the current state it cannot be used for its stated purpose, porting WinForms applications, so even though this is deprecated it needs a fix, otherwise this repository (and its nuget package) are useless.

Simplest fix would be suppressing WindowsBase reference in the project file, alternatively all usage of Size must be explicitly qualified to System.Drawing (or do a `using Size = System.Drawing.Size` at the top of any file referring to `Size` if you want to reduce the number of edits)

If you can't or don't want to fix this please state it at the front page and deprecate the nuget package as well because it doesn't work, in particular the designer attributes referring to sizes are broken.

/cc @RussKie @merriemcgaw since this affects WinForms porting, in case you know who can take care of this (I can do a PR if it helps). This assembly was inbox in Desktop Framework and not having it working in .NET Core is a porting issue.

**Comment by merriemcgaw** [comment]
I think we can make an exception and take this particular fix as it is so egregious. @weltkante you're more than welcome to submit a PR and @RussKie and I will approve it.

**Comment by KlausLoeffelmann** [comment]
Yes, that was an oversight. We had that at countless spots while porting, and that would be the right fix!

**Comment by weltkante** [comment]
Thanks, might still need a manual update of the nuget package (though #11 looks like this is intended to happen at some point anyways)

**Comment by RussKie** [comment]
Thank you for the link!
We're still waiting for the builds to finish...

**Comment by RussKie** [comment]
I have published the new version: https://www.nuget.org/packages/System.Windows.Forms.DataVisualization/1.0.0-prerelease.20110.1
Please let me know if there are ant issues.
